### ISSUE TITLE
addNeededItemToShoppingListItem requires too many attributes

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/collaborative-shopping#14]
`POST /shoppinglists/{id}/items/{item_id}/need` should take only an amount as body parameter, because:

- the item id is already specified in the path,
- the name may not be different from the name of the original item
- the unit should also not be different

Instead of checking (or ignoring) these properties, we could also remove them completely, and simply increase the amount.

**Comment by mrsimpson** [comment]
💯you are correct! 
If it's something this obvious, feel free to directly create a PR (instead of an issue)

**Comment by mrsimpson** [comment]
This has been resolved: New signature: `addNeededItemFromShoppingListItem = (needsListId, shoppingListItem)`
