### ISSUE TITLE
What does code 200 in addNeededItemToShoppingListItem really mean?

### ISSUE THREAD

**Issue by jschirrmacher** [mrsimpson/collaborative-shopping#15]
In the specification, code 200 is described as `request was properly processed but something went wrong`. This is not what I would expect to be reported as 200, which normally means "OK".

I don't really get the meaning of the message, but if "something went wrong", it sounds more like a 4xx or 5xx error.

**Comment by mrsimpson** [comment]
You're absolutely right. This was a copy-error from earlier

**Comment by jschirrmacher** [comment]
Then we need to change the OAS file.
