### ISSUE TITLE
Design API for shopping list

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#3]
Epic link: #1 

## Motivation

Provide a restful API for CRUD on shopping lists and corresponding items.
Each shopping list should have a unique identifier, each item in a shopping list should be unique.
Each item needs a quantity (>0)

## Implementation

Adapt the swaggerfile in the backend-section.

## Out-of-scope

Technical services such as authentication.

**Comment by jschirrmacher** [comment]
I think, we need at least a very simple authentication (e.g. Basic Auth without any check of the password) even in the first step to know at least about the current user. Without that, the API would likely define parameters to distinguish between shopping lists. or the people who want to bring along some of the items.

**Comment by mrsimpson** [comment]
@jschirrmacher 
We need authentication as soon as we need something like `my`.
For the very first draft, I even thought of not keeping anything secret: A user could create lists (generated `uuid`s) => The lists are stored locally (e. g. cookie). Everyone with the uuid can access it.
Thus, for a very first step, I'd leave out authentication for the first sketch.

Was that understandable?

**Comment by jschirrmacher** [comment]
Yes, I think so. You store the own uuid in a cookie and send it as the id for the list on the server, right?
What about using the uuid as a token and send it via header then? 😏
