### ISSUE TITLE
Minor issues in EditItemDialog

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#32]
- [x]  Once a shopping list is opened, it automatically switches to edit mode, which is painful if you just want to check what's on the list
- [x]  If no quantity is given, no Item should be created
- [x]  The ordering of the units of measure should make more sense with respect to usage. Proposal:`pc, g, kg, l, ml`

**Comment by jschirrmacher** [comment]
I cannot reproduce the 1st item in your list. Might come from that I don't have any items in my shopping list when I open it because I didn't manage to store items until now... maybe you can give me some hint?

**Comment by mrsimpson** [comment]
With respect to switching to edit mode: This seems to have to do something with corrupt test data: There was a list item without quantity as first item. This made the UI seemingly switch to edit mode.
=> ignore the above
