### ISSUE TITLE
Compact EditItem component 

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#33]
it should appear in one line:
Input/Label name, Input quantity, label/[select](https://ionicframework.com/docs/api/select) with `pc` defaulted

Clicking outside the item should trigger the save

**Comment by jschirrmacher** [comment]
How should `Clicking outside the item should trigger the save` actually work? 

I would need to add click event handler on each and every other component on the screen and call the `onCreateComplete` method of the `Shopping` component... doesn't seem very clean to me.

So, lets look the other way round. What is the most common way to add items to the list? I suppose, users will enter the items one after each other in 80% of the cases. It would be great to only need one click for each item at most. And I think, this is the actual reason for your requirement, correct?

How about combining the `Click here to add item` link and the `DONE` button into just one? I talk about having the `EditItem` always open and change `DONE` to `ADD`.

I'll add a screenshot of how this could look like.

**Comment by jschirrmacher** [comment]
<img width="657" alt="Bildschirmfoto 2020-03-25 um 07 17 03" src="https://user-images.githubusercontent.com/2821879/77507470-cccf1900-6e68-11ea-905a-cb99a6793261.png">

**Comment by jschirrmacher** [comment]
Maybe even place the `EditItem` below the list? Wdyt?

**Comment by mrsimpson** [comment]
I like the above screenshot 👍 
Editing always on the bottom would make the UI very cumbersome in long lists.
If you move the quantity right-aligned next to the unit, I would be absolutely happy for the time being!

**Comment by jschirrmacher** [comment]
I agree, we keep the `EditItem` on top.

**Comment by mrsimpson** [comment]
With respect to switching to edit mode: This seems to have to do something with corrupt test data: There was a list item without quantity as first item. This made the UI seemingly switch to edit mode.
=> ignore the above

**Comment by mrsimpson** [comment]
Is good enough for the time being, only the focus-stuff is missing.
