### ISSUE TITLE
Go shopping: Split the list as per participants

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#36]
## Motivation

As I approach the cashier, I want to be able to easily sort the items in my cart as per the ones I'm shopping for.

## Implementation

On the UI, of "go shopping", there should be a button to divide the list into sections in which can be seen, which items are being shopped for whom.

```
|---------------------------------|
| V My items                      |
|   Tomatoes 4pc                  |
|   Bananas 3pc                   |
| V Utsav's items                 |
|   Tomatoes 40pc                 |
|---------------------------------|

```

**Comment by vbarzana** [comment]
Can you please describe this more in details? is this button like a toggle? or we divide the screen by default? 
I think it would make sense to have like a sub-list of products for every item, so we know that when we are buying tomatoes, we also pick the ones from the neighbor, but still have no clear idea, can you please come up with some sketch? Here we have to consider usability and also make it very easy for the buyer.

Thanks,
 Victor

**Comment by mrsimpson** [comment]
Yes, we have to find an agreement on the design. I thought it's better to get the issue off my brain prior to deciding how to do this properly. I can't do this in a better graphical way now, but it should work this way as well. Added to the description

**Comment by mrsimpson** [comment]
@vbarzana I explained the usecase mor in detail above and created a separate issue #40 as per your usecase.

**Comment by mrsimpson** [comment]
I sketched an interface method including sample data in  4cd524efb9a3b94ca22b5836658aebb082e8935c .
One question on my head: what about spaces in item names? Would that be an issue? Do we need to introduce a slugified name which serves as "key"?

**Comment by mrsimpson** [comment]
@jschirrmacher It would be super awesome if you could take up this issue. I think it's the most critical one, since it illustrates the USP of our app

**Comment by mrsimpson** [comment]
<img width="375" alt="Bildschirmfoto 2020-04-12 um 01 21 17" src="https://user-images.githubusercontent.com/17176678/79056951-091dba00-7c5c-11ea-8670-f72fa1ef44c9.png">
<img width="375" alt="Bildschirmfoto 2020-04-12 um 01 21 53" src="https://user-images.githubusercontent.com/17176678/79056952-09b65080-7c5c-11ea-899e-cce94eed5645.png">
