### ISSUE TITLE
Rename all collections and attribute names from Upper first to lowercase

### ISSUE THREAD

**Issue by vbarzana** [mrsimpson/collaborative-shopping#38]
Hi guys, currently we have the collections as follows:
Users -> Lists -> Items

This needs to be renamed to:
users -> lists -> items

We have to make sure that this change is also done in the firebaseService, then as we don't have very important data we can just remove everything and start from scratch or migrate the existing data, as you guys wish.

Also, we have to update the Firebase functions @utsavanand2 could you please take care of that?

Best regards,
Victor

**Comment by mrsimpson** [comment]
@vbarzana this is more-or-less a style-question.
I disagree this being a bug (it doesn't do any harm to the function), it just needs to be consistent.
I now refactored everything in Store and firebaseService, so it's really easy to change this lateron.

I'd recommend to shift this to a moment when @utsavanand2 also has the functions in this repo and CI/CD implemented, then we can just do a global "Find and Replace" and we're done.

**Comment by vbarzana** [comment]
Agree with you :) I just wanted to track this because it is important.

**Comment by mrsimpson** [comment]
done with the re-engineering
