### ISSUE TITLE
Centralize state

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#42]
## Motivation

as the app grows, managing state will become more tricky.
It is intended to use the Store as a central entity to manage the state which ich currently spread across all components.

## Implementation proposal

A redux store, which is connected to the firebase (either via firebase hooks or via custom implementations) sounds the route to go.

**Comment by mrsimpson** [comment]
See e. g. 
- https://blog.bitsrc.io/building-a-todo-app-in-react-with-firebase-and-redux-ba3ab53a671b
- https://www.youtube.com/watch?v=j9uHzowJNnk

**Comment by jschirrmacher** [comment]
We already use a central state, managed by MobX. Do you have actual requirements which are not yet to be fulfilled with it? What are the reasons to switch to Redux?

**Comment by mrsimpson** [comment]
I simply do not have a clue how MobX works. I can see some state e. g. in the Shoppings: https://github.com/mrsimpson/ShareMyCart/blob/0083f57a61f828394e280d0dde702d47db5705bd/ui/src/components/shoppings/Shoppings.js#L22 . 
My motivation is to tie Firebase's state toe the state management so that the central state is being update once the DB changes. How would this be done using Mobx?

**Comment by jschirrmacher** [comment]
Just change the content of the Store, all components get the state from there, they observe the parts that they belong to. This is done by the (mostly last) line in each component which looks like

```
export default withRouter(inject('store')(observer(Shoppings)));
```

**Comment by mrsimpson** [comment]
I believe I now understood how MobX centralized state should work. I'll be wiring things up newly so that we also get reactivity. Refactoring as per https://www.robinwieruch.de/react-firebase-mobx-tutorial

**Comment by mrsimpson** [comment]
The architecture has been completely revamped to a full, change-trigger based state management.
The Readme has been [adapted to illustrate the current architecture](https://github.com/sharemycart/sharemycart/commit/61e72335964f496336e83df61aaef316fbbbd54c#diff-04c6e90faac2675aa89e2176d2eec7d8R40-R50)
