### ISSUE TITLE
Interaction design

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#6]
Epic #1 

## Motivation

Provide a simple, mobile capable sketch for a user interface. This can be quite similar to any todo-app, but of course can be more specific.

## Implementation

This issue is considered completed if some visuals in any form have been added to the repo (probably in `/docs`).

**Comment by mrsimpson** [comment]
@mikr0012 like that?

**Comment by mrsimpson** [comment]
@vbarzana as far as I understood, you and your team is doing some mock ups as well. Would be great to see some intermediate states shared here as well

**Comment by vbarzana** [comment]
@mrsimpson we are starting on this based in what is defined in the Swagger document.

**Comment by mrsimpson** [comment]
I do think that for iteration 1, we do not have to surface `/need` to the user: since we’ll focus on getting stuff which is on somebody else’s shopping list, users will als ways interacts via `/shoppinglist `. 

Please also note the bug in the current swagger file, #14.
