### ISSUE TITLE
Find a better project name

### ISSUE THREAD

**Issue by mrsimpson** [mrsimpson/collaborative-shopping#8]
"collaborative-shopping" is lame. it sounds like going for a Saturday clothes shopping.
Find a more sexy name. Ideally soon, so that we can move this repo (potentially to an own org)

**Comment by jschirrmacher** [comment]
Some ideas (just brainstorming):
- CoopShopping (ah, neeh, sounds like an existing shop)
- BuyTogether
- BringAlong
- PleaseBring

**Comment by vbarzana** [comment]
These are some of my ideas as well:

- SharedCart
- UniqueCart
- UniCart
- CollabShop
- Wagon8bor
- ShareWire
- CollabCargo
- ChainShop
- ShopHelper
- ShopAdjutant
- Shoppineer
- Shoppizor
- Cart2us

**Comment by mrsimpson** [comment]
@vbarzana I like the SharedCart idea.

What about
- ShareMyCart
- OurCart

Subtitle: 
_Stay home, stay safe - I'll get it for you!_

**Comment by vbarzana** [comment]
Love it!
![image](https://user-images.githubusercontent.com/3055285/77051748-17194b80-69cc-11ea-8aef-f7b387e9f15d.png)

**Comment by mrsimpson** [comment]
alright, so be it `ShareMyCart`.

**Comment by mrsimpson** [comment]
@vbarzana I recently acquired no-panic.org.
`sharemycart.no-panic.org` would also be ok, I guess

**Comment by vbarzana** [comment]
Perfect! We start with it and later buy the domain.

**Comment by mrsimpson** [comment]
Repo renamed, hopefully soon enough no remotes are lost .
