### ISSUE TITLE
But: Unit of measure not filled for new items

### ISSUE THREAD

**Issue by gregorwolf** [mrsimpson/collaborative-shopping#95]
When I create a new item, select the UOM and confirm with OK:

![Screenshot 2020-04-26 at 10 26 14](https://user-images.githubusercontent.com/2639535/80302211-eeddf300-87a8-11ea-9171-47c847fa7d9d.png)

The field is not filled:

![Screenshot 2020-04-26 at 10 26 21](https://user-images.githubusercontent.com/2639535/80302212-f1404d00-87a8-11ea-8abc-59bcddef0235.png)

**Comment by mrsimpson** [comment]
This is fixed in the meantime (in fact it was the first test-driven-fix ;)
Please reopen if not
